=encoding UTF-8

=head1 NAME

Net::StatsD::XS

=for html
<a href="https://travis-ci.org/JRaspass/Net-StatsD-XS">
    <img src="https://api.travis-ci.org/JRaspass/Net-StatsD-XS.svg">
</a>

=head1 SYNOPSIS

 use Net::StatsD::XS qw/count dec inc/;

 Net::StatsD::XS::set_socket( localhost => 8125 );

 inc 'foo.bar';

 dec 'foo.baz', 10;

 count 'foo.qux', 123;

=head1 COPYRIGHT AND LICENSE

Copyright © James Raspass

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
